server.port=8087

resilience4j.circuitbreaker.instances.paymentApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.paymentApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentApi.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.paymentApi.register-health-indicator=true

logging.level.io.github.resilience4j=DEBUG
